### ISSUE TITLE
Compatibility with Advanced Quick Reply Editors

### ISSUE THREAD

**Issue by cuthulino** [lukasamd/MyBB-Fast_Quote#5]
Fast Quote does not Support, to insert Quotes in the FastReply field if any advanced QuickReplyEditor is installed. With this adv. editors, there is no longer the textarea used to store the text.
This editors were tested by myself on newest mybb version wit fastquote and they did not work:
-Quick Advanced Editor
-Quick Advanced Editor Plus
-Advanced Quick Reply Form
-Handcode like told here: http://myskins.org/Thread-Change-your-Quick-Reply-editor-into-an-advanced-editor

Also i tried different values for the "Quick reply field name" field.

Would be great, if this would work!
Would be worth a donation!

**Comment by lukasamd** [comment]
Currently without any chance - I have a lot of work :(

**Comment by ghost** [comment]
Hi, I'm currently running into the same issue. No advanced quick reply works with fast quote.

Is there any chance you might take a look?
Thanks!

**Comment by lukasamd** [comment]
No, its different plugin and I cant make my compatible with all others. Sorry, but do not have time for that. Feel free to create fix and pull request.
